import type { Metadata } from "next"
import localFont from "next/font/local"
import "../globals.css"
import { SidebarProvider } from "@/components/ui/sidebar"
import { getLocale, getMessages, setRequestLocale } from "next-intl/server"
import { NextIntlClientProvider } from "next-intl"
import { ToastProvider } from "@/components/providers/toast-provider"

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const locale = await getLocale()
  const messages = await getMessages()
  const dir = locale == "ar" ? "rtl" : "ltr"

  // Enable static rendering
  setRequestLocale(locale)

  return (
    <html lang={locale} dir={dir}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <SidebarProvider>
            <ToastProvider />
            {children}
          </SidebarProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
